# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_scenario',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community_scenario',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('content', models.TextField(blank=True, null=True)),
                ('s_comment_num', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment_scenario',
            name='c_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community_scenario'),
        ),
    ]
