# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20161214_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_scenario',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='report/'),
        ),
    ]
