# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerlog',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('problem_num', models.IntegerField(null=True)),
                ('problem_title', models.CharField(max_length=50, null=True)),
                ('submit_answer', models.CharField(max_length=100, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('artifact', models.PositiveSmallIntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True)),
                ('level', models.PositiveSmallIntegerField(null=True)),
                ('right_answer', models.CharField(max_length=100, null=True)),
                ('submits', models.IntegerField(blank=True, null=True)),
                ('corrects', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('importance', models.PositiveSmallIntegerField(null=True)),
                ('difficulty', models.PositiveSmallIntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('downfile', models.FileField(blank=True, null=True, upload_to=b'')),
                ('content', models.TextField(blank=True, null=True)),
                ('solve_user', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
