# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snum', models.IntegerField(null=True)),
                ('answer_num', models.IntegerField(null=True)),
                ('answer1', models.CharField(max_length=100, null=True)),
                ('answer2', models.CharField(max_length=100, null=True)),
                ('answer3', models.CharField(max_length=100, null=True)),
                ('answer4', models.CharField(max_length=100, null=True)),
                ('answer5', models.CharField(max_length=100, null=True)),
                ('answer6', models.CharField(max_length=100, null=True)),
                ('answer7', models.CharField(max_length=100, null=True)),
                ('answer8', models.CharField(max_length=100, null=True)),
                ('answer9', models.CharField(max_length=100, null=True)),
                ('answer10', models.CharField(max_length=100, null=True)),
                ('answer11', models.CharField(max_length=100, null=True)),
                ('answer12', models.CharField(max_length=100, null=True)),
                ('answer13', models.CharField(max_length=100, null=True)),
                ('answer14', models.CharField(max_length=100, null=True)),
                ('answer15', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
