# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20161214_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
